### ISSUE TITLE
Importing into TS ES2022 project

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [digitalbazaar/vc-revocation-list#28]
I tried all varieties of imports and tsconfigs, but the outcome stays the same:

```ts
// @ts-ignore
import * as vcRevocationList from 'vc-revocation-list';
import vcRevocationList from 'vc-revocation-list';
import * as pkg from 'vc-revocation-list';
const { createList } = pkg;
```

When trying to use the library in a typescript project the only thing that is imported is an Object with empty defaults

`[Module: null prototype] { default: {} }` which then of course results in the error `TypeError: vcRevocationList.createList is not a function` when running the code

What am i getting wrong using the library here?

**Comment by F-Node-Karlsruhe** [comment]
After a lot of tweaking it appears that using https://www.npmjs.com/package/esm may be outdated. I am sadly unable to make the library work in my typescript project. maybe the used esm module is simply too old as it has not been maintained for 4 years?

**Comment by F-Node-Karlsruhe** [comment]
Probably closely related to https://github.com/digitalbazaar/ed25519-signature-2020/issues/8

**Comment by aljones15** [comment]
vc revocation list doesn't use ESM actually: https://github.com/digitalbazaar/vc-revocation-list/blob/main/package.json

At least the latest version doesn't.  Which version of this library are you using? Maybe an `npm ls -a` would reveal which dependency is using `esm` still? Feel free to file PRs removing `esm` if you see them in a dependency. The issue could be something else though.

I think your issue is that you're not using the `@namespace` version of this library:

https://www.npmjs.com/package/@digitalbazaar/vc-revocation-list

**Comment by F-Node-Karlsruhe** [comment]
That did the trick. I guess i dug too deep before checking the obvious.
Using the namespace version fixed the issue. Thank you!
